[package]
name = "audiometer"
version = "0.1.0"
authors = ["buckle2000 <buckle2000@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.14.0"
libpulse-simple-binding = "2.14.0"
